# Generated by Django 5.2 on 2025-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_config_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
