# Generated by Django 5.2 on 2025-07-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_config_api', '0004_serverconfig_is_container'),
        ('service_config_api', '0002_serviceconfig_is_deprecated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconfig',
            name='cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='serviceconfig',
            name='script',
        ),
        migrations.AddField(
            model_name='serviceconfig',
            name='server_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_config_api.serverconfig'),
        ),
    ]
