# Generated by Django 5.2 on 2025-07-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_config_api', '0004_serverconfig_is_container'),
        ('service_config_api', '0004_alter_serviceconfig_server_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='server_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_config_api.serverconfig'),
        ),
    ]
