# Generated by Django 5.2 on 2025-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_config_api', '0006_alter_serviceconfig_server_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfig',
            name='ansible_script',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
