version: "3.9"

services:
  django:
    image: "${REGISTRY_URL}/server:${ENV}-latest"
    container_name: "server_${ENV}"
    restart: always
    environment:
      ENV: "${ENV}"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      PG_CONN_STR: "${PG_CONN_STR}"
      SECRET_KEY: "${SECRET_KEY}"
      DEBUG: "False"
      KEYCLOAK_SERVER_URL: "${KEYCLOAK_SERVER_URL}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      KEYCLOAK_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      KEYCLOAK_AUDIENCE: "${KEYCLOAK_AUDIENCE}"
      KEYCLOAK_ALGORITHM: "${KEYCLOAK_ALGORITHM}"
      KEYCLOAK_ISSUER: "${KEYCLOAK_ISSUER}"
      KEYCLOAK_VERIFY_TOKENS_WITH_KEYCLOAK: "${KEYCLOAK_VERIFY_TOKENS_WITH_KEYCLOAK}"
      KEYCLOAK_PERMISSION_PATH: "${KEYCLOAK_PERMISSION_PATH}"
      KEYCLOAK_USER_ID_FIELD: "${KEYCLOAK_USER_ID_FIELD}"
      KEYCLOAK_USER_ID_CLAIM: "${KEYCLOAK_USER_ID_CLAIM}"
      KEYCLOAK_CLAIM_MAPPING_FIRST_NAME: "${KEYCLOAK_CLAIM_MAPPING_FIRST_NAME}"
      KEYCLOAK_CLAIM_MAPPING_LAST_NAME: "${KEYCLOAK_CLAIM_MAPPING_LAST_NAME}"
      KEYCLOAK_CLAIM_MAPPING_EMAIL: "${KEYCLOAK_CLAIM_MAPPING_EMAIL}"
      KEYCLOAK_CLAIM_MAPPING_USERNAME: "${KEYCLOAK_CLAIM_MAPPING_USERNAME}"
      KEYCLOAK_CLAIM_MAPPING_SUB: "${KEYCLOAK_CLAIM_MAPPING_SUB}"
      EMAIL_BACKEND: "${EMAIL_BACKEND}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
      EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
      DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
      ANSIBLE_AUTH: "${ANSIBLE_AUTH}"
      #TF_SSH_PRIV_PATH: "${TF_SSH_PRIV_PATH}"
      #TF_SSH_PUB: "${TF_SSH_PUB}"
      HETZNER_API_KEY: "${HETZNER_API_KEY}"
    #entrypoint: /app/entrypoint.sh

    ports:
      - "127.0.0.1:${PORT}:8000"
    volumes:
      - ./id_rsa_tf:/root/.ssh/id_rsa:ro
      - ./id_rsa_tf.pub:/root/.ssh/id_rsa.pub:ro