# Generated by Django 5.2 on 2025-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlattformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recharge_times', models.PositiveIntegerField(default=0)),
                ('coin_limit', models.PositiveIntegerField(default=0)),
                ('internal_user_implementation', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plattform_settings',
            },
        ),
    ]
