# Generated by Django 5.2 on 2025-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'maintenance_messages',
            },
        ),
    ]
