# Generated by Django 5.2 on 2025-05-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0002_maintenancemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'scheduled_credits',
            },
        ),
    ]
