# Generated by Django 5.2 on 2025-05-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
