# Generated by Django 5.2 on 2025-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0005_maintenancemessage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='content_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
