# Generated by Django 5.2 on 2025-08-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0006_log_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plattformsettings',
            name='internal_user_implementation',
        ),
    ]
