# Generated by Django 5.2 on 2025-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0007_remove_plattformsettings_internal_user_implementation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plattformsettings',
            name='recharge_times',
        ),
        migrations.AddField(
            model_name='plattformsettings',
            name='recharge_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plattformsettings',
            name='recharge_interval',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
