# Generated by Django 5.2 on 2025-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0008_remove_plattformsettings_recharge_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plattformsettings',
            name='last_recharge',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
