# Generated by Django 5.2 on 2025-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0009_plattformsettings_last_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plattformsettings',
            name='coin_limit',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
