# Generated by Django 5.2 on 2025-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0010_alter_plattformsettings_coin_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plattformsettings',
            name='coin_limit',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
