# Generated by Django 5.2 on 2025-08-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0011_alter_plattformsettings_coin_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plattformsettings',
            name='recharge_interval',
            field=models.IntegerField(default=7),
        ),
    ]
