# Generated by Django 5.2 on 2025-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_api', '0012_alter_plattformsettings_recharge_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
