# Generated by Django 5.1.7 on 2025-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
