# Generated by Django 5.2 on 2025-04-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0006_remove_project_members_projectmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
