# Generated by Django 5.2 on 2025-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0009_invitation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table='projects_invitations',
        ),
    ]
