"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decouple import config
from pathlib import Path

KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.RemoteUserOpenIdConnectProfile'
KEYCLOAK_REMOTE_USER_MODEL = 'django_keycloak.remote_user.KeycloakRemoteUser'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [".studyserve.de"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_keycloak',
    'corsheaders',
    'rest_framework',
    'server_api',
    'user_api',
    'server_config_api',
    'management_api',
    'project_api',
    'service_api',
    'service_config_api',
    'django_q',
    'mailer',
]

MIDDLEWARE = [
    'drf_keycloak.middleware.HeaderMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "drf_keycloak.authentication.KeycloakAuthBackend",
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.custom_pagesize_pagination.CustomPageSizePagination',
    'PAGE_SIZE': 25,
}

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_api.User'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CORS_ALLOWED_ORIGINS = [    
    'https://webapp.studyserve.de',
]

LOGIN_URL = 'keycloak_login'

KEYCLOAK_CONFIG = {
    "SERVER_URL": config('KEYCLOAK_SERVER_URL'),
    "REALM": config('KEYCLOAK_REALM'),
    "CLIENT_ID": config('KEYCLOAK_CLIENT_ID'),
    "CLIENT_SECRET": config('KEYCLOAK_CLIENT_SECRET'),
    "AUDIENCE": config('KEYCLOAK_AUDIENCE'),
    "ALGORITHM": config('KEYCLOAK_ALGORITHM'),
    "ISSUER": config('KEYCLOAK_ISSUER'),
    "VERIFY_TOKENS_WITH_KEYCLOAK": config('KEYCLOAK_VERIFY_TOKENS_WITH_KEYCLOAK', cast=bool),
    "PERMISSION_PATH": config('KEYCLOAK_PERMISSION_PATH'),
    "USER_ID_FIELD": config('KEYCLOAK_USER_ID_FIELD'),
    "USER_ID_CLAIM": config('KEYCLOAK_USER_ID_CLAIM'),

    "CLAIM_MAPPING": {
        "first_name": config('KEYCLOAK_CLAIM_MAPPING_FIRST_NAME'),
        "last_name": config('KEYCLOAK_CLAIM_MAPPING_LAST_NAME'),
        "email": config('KEYCLOAK_CLAIM_MAPPING_EMAIL'),
        "username": config('KEYCLOAK_CLAIM_MAPPING_USERNAME'),
        "keycloak_id": config('KEYCLOAK_CLAIM_MAPPING_SUB'),
    },
}

Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 6,
    'timeout': 300,
    'retry': 360,
    'queue_limit': 500,
    'bulk': 10,
    'max_attempts': 2,
    'orm': 'default'
}

EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")