# Generated by Django 5.2 on 2025-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0004_alter_service_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
