# Generated by Django 5.2 on 2025-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0005_service_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='expiry_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
