# Generated by Django 5.2 on 2025-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0006_alter_service_expiry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
