# Generated by Django 5.2 on 2025-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0007_service_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLog',
        ),
    ]
