# Generated by Django 5.2 on 2025-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0008_delete_servicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='domain_prefix',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
