# Generated by Django 5.2 on 2025-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0009_service_domain_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_containerized',
            field=models.BooleanField(default=False),
        ),
    ]
