# Generated by Django 5.2 on 2025-07-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0010_service_is_containerized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_containerized',
        ),
    ]
