# Generated by Django 5.2 on 2025-07-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0011_remove_service_is_containerized'),
        ('service_config_api', '0002_serviceconfig_is_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_config_api.serviceconfig'),
        ),
    ]
