# Generated by Django 5.2 on 2025-07-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0012_alter_service_service_config'),
        ('service_config_api', '0002_serviceconfig_is_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_config_api.serviceconfig'),
        ),
    ]
