# Generated by Django 5.2 on 2025-07-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0013_alter_service_service_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='world_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
