# Generated by Django 5.2 on 2025-07-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0014_service_world_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='domain_prefix',
            new_name='domain',
        ),
    ]
