# Generated by Django 5.2 on 2025-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0015_rename_domain_prefix_service_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
