# Generated by Django 5.2 on 2025-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0016_service_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
