# Generated by Django 5.2 on 2025-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0017_service_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vps_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
