# Generated by Django 5.2 on 2025-08-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0018_service_vps_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='project',
            new_name='project_id',
        ),
    ]
