# Generated by Django 5.2 on 2025-08-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0019_rename_project_service_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='project_id',
            new_name='project',
        ),
    ]
