# Generated by Django 5.2 on 2025-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0020_rename_project_id_service_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hostname',
            field=models.CharField(max_length=63),
        ),
    ]
