# Generated by Django 5.1.7 on 2025-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('cpu_cores', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('disk_gb', models.IntegerField()),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'server_configs',
            },
        ),
    ]
