# Generated by Django 5.1.7 on 2025-04-01 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_config_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='cpu_cores',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='disk_gb',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='ram_gb',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
