# Generated by Django 5.2 on 2025-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_config_api', '0002_alter_serverconfig_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
