# Generated by Django 5.2 on 2025-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_config_api', '0003_serverconfig_is_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='is_container',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
