# Generated by Django 5.1.7 on 2025-03-31 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('server_config_id', models.IntegerField()),
                ('expiry_timestamp', models.IntegerField()),
                ('ssh_keys', models.JSONField()),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='creating', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
