# Generated by Django 5.1.7 on 2025-03-31 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0002_alter_server_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
