# Generated by Django 5.1.7 on 2025-04-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0003_server_created_at'),
        ('server_config_api', '0002_alter_serverconfig_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_config_api.serverconfig'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(default='creating', max_length=20, null=True),
        ),
    ]
