# Generated by Django 5.1.7 on 2025-04-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0004_alter_server_server_config_id_alter_server_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_config_id',
            new_name='server_config',
        ),
    ]
