# Generated by Django 5.1.7 on 2025-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0005_rename_server_config_id_server_server_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(blank=True, default='creating', max_length=20),
        ),
    ]
