# Generated by Django 5.1.7 on 2025-04-01 15:12

import server_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0008_alter_server_ssh_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ssh_keys',
            field=models.JSONField(validators=[server_api.models.validate_ssh_keys]),
        ),
    ]
