# Generated by Django 5.1.7 on 2025-04-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0009_alter_server_ssh_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_api.server')),
            ],
            options={
                'db_table': 'server_logs',
            },
        ),
    ]
