# Generated by Django 5.1.7 on 2025-04-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
        ('server_api', '0010_serverlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='project_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='project_api.project'),
            preserve_default=False,
        ),
    ]
