# Generated by Django 5.1.7 on 2025-04-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
        ('server_api', '0011_alter_server_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='project_id',
        ),
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_api.project'),
        ),
    ]
