# Generated by Django 5.1.7 on 2025-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0012_remove_server_project_id_server_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='owner',
        ),
    ]
