# Generated by Django 5.2 on 2025-04-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0015_alter_server_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
