# Generated by Django 5.2 on 2025-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0016_server_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
