# Generated by Django 5.2 on 2025-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0017_server_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
