# Generated by Django 5.2 on 2025-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0018_alter_server_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='vps_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
