# Generated by Django 5.2 on 2025-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0019_server_vps_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='world_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
