# Generated by Django 5.2 on 2025-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0020_server_world_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'ansible_scripts',
            },
        ),
    ]
