# Generated by Django 5.2 on 2025-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0021_ansiblescript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='world_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
