# Generated by Django 5.2 on 2025-05-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0022_alter_server_world_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
