# Generated by Django 5.2 on 2025-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0023_server_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expiry_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
