# Generated by Django 5.2 on 2025-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0024_alter_server_expiry_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerLog',
        ),
    ]
