# Generated by Django 5.2 on 2025-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0025_delete_serverlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblescript',
            name='parameters',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
