# Generated by Django 5.2 on 2025-07-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0026_ansiblescript_parameters'),
        ('server_config_api', '0004_serverconfig_is_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server_config_api.serverconfig'),
        ),
    ]
