# Generated by Django 5.2 on 2025-07-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0027_alter_server_server_config'),
        ('server_config_api', '0004_serverconfig_is_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_config_api.serverconfig'),
        ),
    ]
