# Generated by Django 5.2 on 2025-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0028_alter_server_server_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
