# Generated by Django 5.2 on 2025-08-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0029_server_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansiblescript',
            name='parameters',
        ),
    ]
