# Generated by Django 5.2 on 2025-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0030_remove_ansiblescript_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=63),
        ),
    ]
