# Generated by Django 5.2 on 2025-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0031_alter_server_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='vps_status',
            field=models.CharField(blank=True, default='offline', max_length=20, null=True),
        ),
    ]
