# Generated by Django 5.1.7 on 2025-03-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_user_managers_user_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
