# Generated by Django 5.2 on 2025-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0010_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
